// Code generated by "stringer -type=TokenType"; DO NOT EDIT.

package scanner

import "fmt"

const _TokenType_name = "T_LEFT_PARENT_RIGHT_PARENT_LEFT_BRACET_RIGHT_BRACET_COMMAT_DOTT_MINUST_PLUST_SEMICOLONT_SLASHT_START_BANGT_BANG_EQUALT_EQUALT_EQUAL_EQUALT_GREATERT_GREATER_EQUALT_LESST_LESS_EQUALT_IDENTIFIERT_STRINGT_NUMBERT_ANDT_CLASST_ELSET_FALSET_FUNT_FORT_IFT_NILT_ORT_PRINTT_RETURNT_SUPERT_THIST_TRUET_VART_WHILET_EOF"

var _TokenType_index = [...]uint16{0, 12, 25, 37, 50, 57, 62, 69, 75, 86, 93, 99, 105, 117, 124, 137, 146, 161, 167, 179, 191, 199, 207, 212, 219, 225, 232, 237, 242, 246, 251, 255, 262, 270, 277, 283, 289, 294, 301, 306}

func (i TokenType) String() string {
	if i < 0 || i >= TokenType(len(_TokenType_index)-1) {
		return fmt.Sprintf("TokenType(%d)", i)
	}
	return _TokenType_name[_TokenType_index[i]:_TokenType_index[i+1]]
}
